<a href="https://colab.research.google.com/github/SChiu-project/CUSCS-m3/blob/main/Class5_Tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
import cv2
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math
%matplotlib inline

Try Tensor

Tensor means matrix

In [ ]:
var_string = tf.constant('hello, tensorflow')
print(var_string)

tf.Tensor(b'hello, tensorflow', shape=(), dtype=string)


In [ ]:
var_x = tf.Variable([1.,2.], name='x')
print(var_x)

<tf.Variable 'x:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>


In [ ]:
# convert numpy to tensor flow
a = tf.constant(np.array([1.,2.,3.]))
b = tf.constant(np.array([4.,5.,6.]))
c = tf.add(a,b)
c

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([5., 7., 9.])>

In [ ]:
c.shape

TensorShape([3])

In [ ]:
# convert tensor to numpy
c.numpy()

array([5., 7., 9.])

1D Tensor

In [ ]:
# create a numpy array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
# convert numpy to tensor
c = tf.convert_to_tensor(a)
c

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
b = np.array([4,5,6], dtype='int32')
b
# convert to int 32, for saving ram

array([4, 5, 6], dtype=int32)

In [ ]:
d = tf.convert_to_tensor(b)
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

2D Tensor

In [ ]:
c = tf.ones([2,3])
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
d = tf.zeros([2,3])
d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
# chnage the data type of variable
e = tf.cast(d, tf.float16)
e

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float16)>

transpose

In [ ]:
f = tf.random.uniform(shape=(3,5))
g = tf.transpose(f)
print(f)
print(g)

tf.Tensor(
[[0.36577785 0.5543475  0.8986137  0.49880815 0.4334066 ]
 [0.9739239  0.24204206 0.17454362 0.17366874 0.45651615]
 [0.48447752 0.23100662 0.90177214 0.06771004 0.8050498 ]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0.36577785 0.9739239  0.48447752]
 [0.5543475  0.24204206 0.23100662]
 [0.8986137  0.17454362 0.90177214]
 [0.49880815 0.17366874 0.06771004]
 [0.4334066  0.45651615 0.8050498 ]], shape=(5, 3), dtype=float32)


Reshape

In [ ]:
h = tf.zeros((30,))
h

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
g = tf.reshape(h, shape = (5,6))
g

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
j = tf.zeros([1,2,1,3,1])
j

<tf.Tensor: shape=(1, 2, 1, 3, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]]]]], dtype=float32)>

In [ ]:
k = tf.squeeze(j, axis =[2,2])
k

<tf.Tensor: shape=(1, 2, 3, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]]], dtype=float32)>