<a href="https://colab.research.google.com/github/SChiu-project/CUSCS-m3/blob/main/Class4_data_preparation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

In [ ]:
feature = np.array([
    ["Texas"],
    ["California"],
    ["Texas"],
    ["Delaware"],
    ["Texas"]
])

In [ ]:
feature

array([['Texas'],
       ['California'],
       ['Texas'],
       ['Delaware'],
       ['Texas']], dtype='<U10')

In [ ]:
len(feature)

5

In [ ]:
type(feature)

numpy.ndarray

In [ ]:
np.unique(feature)

array(['California', 'Delaware', 'Texas'], dtype='<U10')

In [ ]:
# create one-hot encoder
one_hot = LabelBinarizer()

# one-hot encode feature
one_hot_result = one_hot.fit_transform(feature)
print(one_hot_result)

[[0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]]


In [ ]:
type(one_hot_result)

numpy.ndarray

In [ ]:
# view feature classes
print(one_hot.classes_)

['California' 'Delaware' 'Texas']


In [ ]:
# reverse one-hot encoding
one_hot_reverse = one_hot.inverse_transform(one_hot.transform(feature))
print(one_hot_reverse)

['Texas' 'California' 'Texas' 'Delaware' 'Texas']


In [ ]:
# reverse one-hot encoding method 2
one_hot_reverse = one_hot.inverse_transform(one_hot_result)
print(one_hot_reverse)

['Texas' 'California' 'Texas' 'Delaware' 'Texas']


In [ ]:
import pandas as pd
df = pd.get_dummies(feature[:, 0])
print(df)

   California  Delaware  Texas
0           0         0      1
1           1         0      0
2           0         0      1
3           0         1      0
4           0         0      1


In [ ]:
# create multiclass feature
multiclass_feature = [
    ("Texas", "Florida"),
    ("California", "Alabama"),
    ("Texas", "Florida"),
    ("Delaware", "Florida"),
    ("Texas", "Alabama")
]

# create multiclass one-hot encoder
one_hot_multiclass = MultiLabelBinarizer()

# one-hot encode multiclass feature
one_hot_multi = one_hot_multiclass.fit_transform(multiclass_feature)

print(one_hot_multi)

[[0 0 0 1 1]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [0 0 1 1 0]
 [1 0 0 0 1]]


In [ ]:
len(one_hot_multi)

5

In [ ]:
# view classes
# ordered by alphabet
print(one_hot_multiclass.classes_)

['Alabama' 'California' 'Delaware' 'Florida' 'Texas']


In [ ]:
# create features
df = pd.DataFrame({"Score": ["Low", "Low", "Medium", "Medium", "High"]})

# create mapper
scale_mapper = {
    "Low": 1,
    "Medium": 2,
    "High": 3
}

# replace feature values with scale
df = df["Score"].replace(scale_mapper)
print(df)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64


In [ ]:
from sklearn.feature_extraction import DictVectorizer

data_dict = [
    {"Red": 2, "Blue": 4},
    {"Red": 4, "Blue": 3},
    {"Red": 1, "Yellow": 2},
    {"Red": 2, "Yellow": 2}
]

# create dictionary vectorizer
dictvectorizer = DictVectorizer(sparse=False)

# convert dictionary to feature matrix
features = dictvectorizer.fit_transform(data_dict)

print(features)

# [4.2.0.] means Blue:4, Red: 2, Yellow:0

[[4. 2. 0.]
 [3. 4. 0.]
 [0. 1. 2.]
 [0. 2. 2.]]


In [ ]:
# get feature names
features = dictvectorizer.get_feature_names_out()
print(features)

['Blue' 'Red' 'Yellow']


In [ ]:
# predict missing values' class
from sklearn.neighbors import KNeighborsClassifier

X = np.array([[0, 2.10, 1.45],
            [1, 1.18, 1.33],
            [0, 1.22, 1.27],
            [1, -0.21, -1.19]])

X_with_nan = np.array([[np.nan, 0.87, 1.31],
                      [np.nan, -0.67, -0.22]])

# train KNN learner
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X[:,1:], X[:, 0])

# predict missing values' class
imputed_values = trained_model.predict(X_with_nan[:, 1:])

# join column of predicted class with their other features
X_with_imputed = np.hstack((imputed_values.reshape(-1, 1), X_with_nan[:, 1:]))

# join two feature matricies
imputed = np.vstack((X_with_imputed, X))
print(imputed)

[[ 0.    0.87  1.31]
 [ 1.   -0.67 -0.22]
 [ 0.    2.1   1.45]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.21 -1.19]]


In [ ]:
# from sklearn.preprocessing import Imputer
from sklearn.impute import SimpleImputer

# join the two feature matricies
X_complete = np.vstack((X_with_nan, X))
# print(X_complete)

# imputer = Imputer(strategy='most_frequent', axis=0)
imputer = SimpleImputer(missing_values= np.nan, strategy='most_frequent')

imputer.fit(X_complete)
result = imputer.transform(X_complete)
print(result)

[[ 0.    0.87  1.31]
 [ 0.   -0.67 -0.22]
 [ 0.    2.1   1.45]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.21 -1.19]]


In [ ]:
# convert to 1 or 0
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

iris = load_iris()

features = iris.data
target = iris.target

# print(features)
print(target)
# print(len(features), len(target))

target = np.where((target == 0), 0, 1)
print(target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [ ]:
# to use where function
iris = load_iris()

features = iris.data
target = iris.target

# print(features)
print(target)
# print(len(features), len(target))

# create binary target vector indicating if class 0
target = np.where((target == 2), 6, 3)
print(target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6]


In [ ]:
iris = load_iris()

features = iris.data
target = iris.target

# # remove first 40 observations
# features = features[40:, :]
# target = target[40:]

# create binary target vector indicating if class 0
target = np.where((target == 0), 0, 1)
# print(target)

# create weights
weights = {0: .9, 1: 0.1}

random_forest_classifier = RandomForestClassifier(class_weight=weights)
# print(random_forest_classifier)

random_forest_balanced = RandomForestClassifier(class_weight="balanced")
# print(random_forest_balanced)


i_class0 = np.where(target == 0)[0]
i_class1 = np.where(target == 1)[0]
print(i_class0)
print(i_class1)

n_class0 = len(i_class0)
n_class1 = len(i_class1)
print('class 0:', n_class0)
print('class 1:', n_class1)

i_class1_downsampled = np.random.choice(i_class1, size=n_class0, replace=False)
print(i_class1_downsampled)

print(np.hstack((target[i_class0], target[i_class1_downsampled])))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149]
class 0: 50
class 1: 100
[143  71 100  87  85  70 110 101 148 138 147 136 139 106 120  93 128  74
 132 124  82  91  75  51  53  65  64 134  97 102 104 107 129 114  62  73
 142  54  60 116 127 125 126 108 140  69  63 131 144 123]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
#
from io import StringIO
import sys
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,,12.0,
,,,'''


print(csv_data)


A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,,12.0,
,,,


In [ ]:
df = pd.read_csv(StringIO(csv_data))
df

A    B     C    D
0   1.0  2.0   3.0  4.0
1   5.0  6.0   NaN  8.0
2  10.0  NaN  12.0  NaN
3   NaN  NaN   NaN  NaN

In [ ]:
#convert df to array
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., nan, 12., nan],
       [nan, nan, nan, nan]])

In [ ]:
df.isnull()

A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3   True   True   True   True

In [ ]:
df.isnull().values

array([[False, False, False, False],
       [False, False,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
# whether get null
df.isnull().values.any()

True

In [ ]:
df.isnull().sum()

A    1
B    2
C    2
D    2
dtype: int64

In [ ]:
# will drop entire row
df2 = df.dropna()
df2

A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
# will drop column
df3 = df.dropna(axis=1)
df3

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [ ]:
# only remove when entire row na
df4 = df.dropna(how='all')
df4

A    B     C    D
0   1.0  2.0   3.0  4.0
1   5.0  6.0   NaN  8.0
2  10.0  NaN  12.0  NaN

In [ ]:
# threhold mini 3 columns contain value (not na)
df5 = df.dropna(thresh=3)
df5

A    B    C    D
0  1.0  2.0  3.0  4.0
1  5.0  6.0  NaN  8.0

In [ ]:
# specific column C got na then drop
df6 = df.dropna(subset=['C'])
df6

A    B     C    D
0   1.0  2.0   3.0  4.0
2  10.0  NaN  12.0  NaN

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(df.values)
imputed_data = imputer.transform(df.values)
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.5       ,  8.        ],
       [10.        ,  4.        , 12.        ,  6.        ],
       [ 5.33333333,  4.        ,  7.5       ,  6.        ]])

In [ ]:
#different approach to achieve above imputer strategy with mean
df7 = df.fillna(df.mean())
df7

A    B     C    D
0   1.000000  2.0   3.0  4.0
1   5.000000  6.0   7.5  8.0
2  10.000000  4.0  12.0  6.0
3   5.333333  4.0   7.5  6.0